### ISSUE TITLE
Update documentation for compatibility with Zero/MKR1000

### ISSUE THREAD

**Issue by q2dg** [arduino-libraries/Scheduler#2]
Due is based on a Cortex-M3 ARM whereas Zero/MKR1000 are based on a Cortex-M0+ ARM chip.
Might it be feasible? Thanks

**Comment by vbextreme** [comment]
It is already conpatibile with zero.

**Comment by sandeepmistry** [comment]
Hi @q2dg,

As @vbextreme mentioned, this library is already compatible with both the Zero and MKR1000. The [0.4.4](https://github.com/arduino-libraries/Scheduler/releases/tag/0.4.4) release added support for these boards, specifically https://github.com/arduino-libraries/Scheduler/commit/2294a27fffd8528335c0ad6eb18a52c85d9395ed.

I noticed both the Zero and MKR1000 were not mentioned in the read me and added this missing information.

**Comment by q2dg** [comment]
Yeah, thanks! 

I think this change should also be mentioned in https://www.arduino.cc/en/Reference/Libraries (in fact, some other libraries from this repo aren't even mentioned in that page meanwhile deprecated ones still do,  but this is another story).

**Comment by q2dg** [comment]
Also, https://www.arduino.cc/en/Reference/Scheduler should be modified...

**Comment by sandeepmistry** [comment]
Hi @q2dg,

Thanks for the outdated reference links! @agdl could you please update them and close this issue?

For the `Reference/Libraries` link, we can move Scheduler from `Due Only Libraries` to `Due, Zero and MKR1000 Libraries`. For the `Reference/Scheduler` you can update it with the same change that I made to the read me.

**Comment by agdl** [comment]
Done thank you!
