### ISSUE TITLE
arduino-libraries / Scheduler Error compiling for board Generic ESP8266 Module.

### ISSUE THREAD

**Issue by alirezash12345** [arduino-libraries/Scheduler#7]
Hi...when I debug this library on esp8266 module, it gives the following error:
Arduino: 1.8.12 (Windows 10), Board: "Generic ESP8266 Module, 160 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), dtr (aka nodemcu), 26 MHz, 40MHz, DOUT (compatible), 4MB (FS:3MB OTA:~512KB), 2, nonos-sdk 2.2.1+100 (190703), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

WARNING: library Scheduler claims to run on sam, samd architecture(s) and may be incompatible with your current board which runs on esp8266 architecture(s).
C:UsersshafieeDocumentsArduinolibrariesSchedulersrcScheduler.cpp: Assembler messages:

C:UsersshafieeDocumentsArduinolibrariesSchedulersrcScheduler.cpp:81: Error: bad register name: r0

C:UsersshafieeDocumentsArduinolibrariesSchedulersrcScheduler.cpp:81: Error: junk at end of line, first unrecognized character is `r'

C:UsersshafieeDocumentsArduinolibrariesSchedulersrcScheduler.cpp:81: Error: bad register name: r5

C:UsersshafieeDocumentsArduinolibrariesSchedulersrcScheduler.cpp:81: Error: junk at end of line, first unrecognized character is `r'

C:UsersshafieeDocumentsArduinolibrariesSchedulersrcScheduler.cpp:81: Error: unknown opcode or format name 'blx'

C:UsersshafieeDocumentsArduinolibrariesSchedulersrcScheduler.cpp:81: Error: extra comma

C:UsersshafieeDocumentsArduinolibrariesSchedulersrcScheduler.cpp:81: Error: syntax error

C:UsersshafieeDocumentsArduinolibrariesSchedulersrcScheduler.cpp:126: Error: bad register name: r12

C:UsersshafieeDocumentsArduinolibrariesSchedulersrcScheduler.cpp:126: Error: junk at end of line, first unrecognized character is `r'

C:UsersshafieeDocumentsArduinolibrariesSchedulersrcScheduler.cpp:126: Internal error in ignore_rest_of_line at /workdir/repo/binutils-gdb/gas/read.c:3762.

Please report this bug.

exit status 1
Error compiling for board Generic ESP8266 Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by per1234** [comment]
As the warning says:
```
WARNING: library Scheduler claims to run on sam, samd architecture(s) and may be incompatible with your current board which runs on esp8266 architecture(s).
```
and the documentation:
https://www.arduino.cc/en/Reference/Scheduler
>The Scheduler library enables an Arduino based on SAM and SAMD architectures (i.e (i.e Zero, MKRZero, MKR1000 Board) and Due) to run multiple functions at the same time.

Your ESP8266 board is not supported by the library.
